{% set version = "3.4.0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scitools-iris/scitools-iris-{{ version }}.tar.gz
  sha256: b294afe20dd16c490cde703a80d461c39b8a2387512b811c27c113c7ab53f31e

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

outputs:
  - name: iris
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools >=64
        - setuptools-scm >=7
      run:
        - python >=3.8
        - cartopy >=0.21
        - cf-units >=3.1
        - cftime >=1.5
        - dask-core >=2.26
        - matplotlib-base >=3.5
        - netcdf4 <1.6.1
        - numpy >=1.19
        - pyproj
        - scipy
        - shapely !=1.8.3
        - python-xxhash

    test:
      imports:
        - iris

  - name: scitools-iris
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('iris', max_pin="x.x.x") }}
    test:
      imports:
        - iris
about:
  home: https://scitools-iris.readthedocs.io/en/stable/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - DPeterK
    - corinnebosley
    - lbdreyer
    - pp-mo
    - jamesp
    - stephenworsley
    - trexfeathers
    - wjbenfold
