{% set version = "3.3.0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: 49943a404f1fe3e90863767de2a77e8465c3f15a0b9e83eee9966b212299553d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

outputs:
  - name: iris
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - cartopy >=0.20
        - cf-units ==3.0.1
        - cftime ==1.5.1.1
        - dask-core >=2
        - matplotlib-base
        - netcdf4 >=1.4
        - numpy >=1.19
        - scipy
        - python-xxhash

    test:
      imports:
        - iris

  - name: scitools-iris
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('iris', max_pin="x.x.x") }}
    test:
      imports:
        - iris
about:
  home: https://scitools-iris.readthedocs.io/en/stable/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - DPeterK
    - corinnebosley
    - lbdreyer
    - pp-mo
    - jamesp
    - stephenworsley
    - trexfeathers
    - wjbenfold
