travis:
  secure:
    BINSTAR_TOKEN: ywt0zV0GdWAHcxjQUpf4D45n7a38QHz99tHjO6UUhWeeh0uPAjKyWvN67m5rbhyVOAzTpMqja5YefudKa0fX6M8wERQ5t4gmEKFtwVnV+5Aof0VBsONhVDmEBrTkCNXdefCpzsitlp9n1yyb8aG8KbbmBhydi4IuxxbNxTNVdh+wfcj6a5Ov13QSQs6WJ5CJzNqQWzwCsoaTW6GjZECH21y4Ux5DlUdiiJ+IbdcKc8SeEQIuE2K7PEI/SVSAoKHNOXdHdp77xy/u97EUFkxeXBXObz4BFt6fHgvXOYcKd9xajqeCvyaPsdEOUfz9m8nlEQAo8TOo25Nt76KxQqR0cDRntegrsGfVdS5UdlzlL3VrVoUHVSOcfRgznx/MK2gkysdolb/Q7KdVsNXPhiBy4KpX5FSYe/dpBGxHQqAX4qHr6/hVIEBZE1MWfkYvKCAewoV0PLE4/ypG8j+B6/2VCo+KDJLobsynYVraArrJlycGHv0fejYknWVCctgwNw4cER/HsOIPPEadMwoz3gN/6uV8soI3vnPAuR98LdHvoTKXpMSIzO13rpSAmGftDYPOkFe9VI5kRQYZX2p3+4f9vKuotyLVV/vLGYebPJTic0eoTcHlQmjWZB1JWzUTArrapSxMyuPrrgnjmipf9w33IW7amk+2g42g5d5JkBY5XWI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
